products = [
    {
        '_id': '1',
        'name': 'Sansevieria Trifasciata Moonshine',
        'image': '/images/moonshine.webp',
        'description': 'Still the most popular houseplants just as they were back in the 70s, and with good reason - they thrive off of neglect and will take whatever you throw at them. This species has delightful silvery tones.',
        'watering': 'Throughout the year allow soil to dry out 90%. Thrives off neglect.',
        'lightRequirements': 'Bright, indirect light, shade tolerant.',
        'category': 'Low Light',
        'price': 38,
        'plantSize': '40cm',
        'countInStock': 6,
        'rating': 5,
        'numReviews': 2,
    },
    {
        '_id': '2',
        'name': 'Sansevieria trifasciata laurentii',
        'image': '/images/laurentii.webp',
        'description': 'The Sansevieria is a real survivor! This amazing, large ‘Mother in-laws tongue’ can make the most of the harshest of conditions - heating, air conditioning, under-watering, neglect. If you need an easy plant you cannot get easier than this. Aside from its laid back nature, let us take a minute to appreciate its long stripy leaves with flashes of bright yellow along the edges, a classic beauty.',
        'watering': 'Throughout the year water only when 90% of the soil is dry. A good tip to remember - if your plant is getting less light then it will need less water.',
        'lightRequirements': 'Bright, indirect. Shade tolerant.',
        'category': 'Low Light',
        'price': 25,
        'plantSize': '60cm',
        'countInStock': 4,
        'rating': 5,
        'numReviews': 11,
    },
    {
        '_id': '3',
        'name': 'Sansevieria trifasciata Gold Flame',
        'image': '/images/goldflame.jpg',
        'description': 'This genus continues to be one of the most revered groups of plants, with avid collectors spread far and wide across the globe. They are easy to grow, tolerant of varying levels of care, and are hugely diverse in leaf design, colour and form. The Dracaena trifasciata ’Gold Flame’ brings a burst of colour and freshness with its bright yellow inner leaves.',
        'watering': 'Allow soil to dry out 90% all year round.',
        'lightRequirements': 'Bright, indirect, shade tolerant.',
        'category': 'Low Light',
        'price': 18,
        'plantSize': '40cm',
        'countInStock': 8,
        'rating': 4.75,
        'numReviews': 7,
    },
    {
        '_id': '4',
        'name': 'Eulychnia castanea f. varispiralis',
        'image': '/images/eulychniamulti.webp',
        'description': 'A prized specimen among collectors, Eulychnia castanea f. varispiralis is an unusual, slow-growing plant with a spiralling helter-skelter form.',
        'watering': 'Water when soil is dry 100%. Water very lightly (if at all) during winter months.',
        'lightRequirements': 'Full sun.',
        'category': 'Full Sun',
        'price': 48,
        'plantSize': '18cm',
        'countInStock': 3,
        'rating': 5,
        'numReviews': 2,
    },
    {
        '_id': '5',
        'name': 'Myrtillocactus geometrizans f.cristata',
        'image': '/images/myrtillo.webp',
        'description': 'This magnificent bright blue cactus grows into wonderful contorted shapes that resemble puffs of smoke. It’s a dense chunky plant that is slow growing and easy going. To keep the growth nice and crested, pop it in the sunniest spot you have.',
        'watering': 'Water when soil is dry 100%. Water lightly (if at all) during winter months.',
        'lightRequirements': 'Full sun.',
        'category': 'Full Sun',
        'price': 39,
        'plantSize': '18cm',
        'countInStock': 1,
        'rating': 5,
        'numReviews': 1,
    },
    {
        '_id': '6',
        'name': 'Tephrocactus geometricus (A. Cast.) Backeb.',
        'image': '/images/tephrocactus_geometricus.webp',
        'description': 'Growing in small clumps in the deserts of Argentina and Bolivia, Tephrocactus geometricus is adapted to extreme heat and drought. The almost spine-free, spherical segments of this rare cactus take on a deep purple under intense sun, and produce fabulous white-pink flowers in summer which last for just a single day.',
        'watering': 'In summer water thoroughly only when 100% of the soil has dried out. A/W allow soil to dry 100% - water sparingly (every three months). Spring gradually increase watering - depending on temp and light exposure.  ',
        'lightRequirements': 'Full sun. ',
        'category': 'Full Sun',
        'price': 126,
        'plantSize': '20cm',
        'countInStock': 3,
        'rating': 4.5,
        'numReviews': 5,
    },
    {
        '_id': '7',
        'name': 'Bucida buceras Shady Lady (black olive tree)',
        'image': '/images/bucidabuceras.jpg',
        'description': 'This tropical tree is native to Central and South America, and requires plenty of light, and room to grow. Bucida buceras is more commonly known as ‘The Shady Lady’ or ‘black olive tree’. Greatly desired for its architectural silhouette; slim trunk, slightly drooping branches, with glossy-green, delicate leaves that cluster at the tips of the branches. These highly sought after statement plants are slow growing but can grow up to 20 metres tall. ',
        'watering': 'In S/S water when 20% of the top soil has dried out. In A/W allow top soil to dry out 50%. Keep moist but well-drained.',
        'lightRequirements': 'Full sun (or light shade). South, west, or east facing window ideally. ',
        'category': 'Full Sun',
        'price': 669,
        'plantSize': '250cm',
        'countInStock': 7,
        'rating': 5,
        'numReviews': 1,
    },
    {
        '_id': '8',
        'name': 'Philodendron melanochrysum',
        'image': '/images/melano.webp',
        'description': 'Philodendron mamei grows large, delicately rippled leaves with subtle streaks of variegation across the surface. This Philodendron loves to climb and will reward you with bigger, more dramatic leaves if given a moss pole or support stick to wrap around.',
        'watering': 'In S/S water when 20% of the top soil has dried out. In A/W allow top soil to dry out 50%. A high humidity lover so mist often.',
        'lightRequirements': 'Bright, indirect.',
        'category': 'Full Sun',
        'price': 46,
        'plantSize': '30cm',
        'countInStock': 5,
        'rating': 5,
        'numReviews': 2,
    },
    {
        '_id': '9',
        'name': 'Cleistocactus colademononis',
        'image': '/images/cleisto.webp',
        'description': 'The Cleistocactus colademononis or "Monkey tail" cactus is a fast growing Lithophyte with curling tail-like stems which are white/gingery and really as soft as they look, making it the loveliest cacti to work with and have in your home. If that was not enough it also has a flourish of pink flowers in early summer. Larger pot size (over 12cm) will feature multiple stem, smaller pot size will have a single stem.',
        'watering': 'In summer water thoroughly only when 100% of the soil has dried out. A/W allow soil to dry 100% - water sparingly (every two months). In spring gradually increase watering - depending on temperature and light exposure.',
        'lightRequirements': 'Full sun.',
        'category': 'Full Sun',
        'price': 35,
        'plantSize': '25cm',
        'countInStock': 1,
        'rating': 4,
        'numReviews': 1,
    },
    {
        '_id': '10',
        'name': 'Sansevieria Sayuri Metallica ‘Siam silver’',
        'image': '/images/silversiam.jpg',
        'description': 'Sansevieria “Metallica Siam Silver” is a perennial stemless succulent plant that has linear, pointed leaves which occur in rosettes. Leaves are stiff, leathery which are held erect & wide.They have a vertical striping pattern of grey and greyish green bands of varying width with Horizontal bands of light greyish green crossing through the greyish green vertical bands.Siam Silver are also known as ‘Tom Grumbley’.',
        'watering': 'Before watering one need to check to see if the plant is ready to be watered by putting your finger 1-2 inches deep into the soil. If it is dry, then it is time to water the plant, otherwise not to water the plant.',
        'lightRequirements': 'Bright, indirect light, shade tolerant.',
        'category': 'Low Light',
        'price': 20,
        'plantSize': '50cm',
        'countInStock': 9,
        'rating': 4.5,
        'numReviews': 6,
    },
]
