# Generated by Django 5.0.7 on 2024-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='lightRequirements',
        ),
        migrations.AddField(
            model_name='product',
            name='watering',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
