# Generated by Django 5.0.7 on 2024-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plantSize',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
