# Generated by Django 5.0.7 on 2024-08-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_plantsize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAdress',
            new_name='ShippingAddress',
        ),
        migrations.AlterField(
            model_name='product',
            name='watering',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
